version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: dev
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    target-branch: dev
    directory: "/"
    schedule:
      interval: "weekly"
